name: me
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animated_text_kit: ^4.2.3
  animated_theme_switcher: ^2.0.10
  cached_network_image: ^3.4.1
  dotted_border: ^2.1.0
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  lucide_icons_flutter: ^1.2.7
  mouse_follower: ^1.3.7
  provider: ^6.1.2
  rive: ^0.13.20
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/rive/
    
