// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnnmYOADL2XoSSVyP9wxPo5ZmiuNiWz5Y',
    appId: '1:924490567049:web:59e1c0dfc0e901e6dca558',
    messagingSenderId: '924490567049',
    projectId: 'x-me-297fb',
    authDomain: 'x-me-297fb.firebaseapp.com',
    storageBucket: 'x-me-297fb.firebasestorage.app',
    measurementId: 'G-EQ28NT74ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClkUqH3T6sswR--amfVG_sNvHoBolF4NI',
    appId: '1:924490567049:android:0e7d6981341999a5dca558',
    messagingSenderId: '924490567049',
    projectId: 'x-me-297fb',
    storageBucket: 'x-me-297fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ9SuSxuv6iJvH6SZg7CUwbRDpC8pB8lY',
    appId: '1:924490567049:ios:2b8c2496aa96fddddca558',
    messagingSenderId: '924490567049',
    projectId: 'x-me-297fb',
    storageBucket: 'x-me-297fb.firebasestorage.app',
    iosBundleId: 'com.example.me',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ9SuSxuv6iJvH6SZg7CUwbRDpC8pB8lY',
    appId: '1:924490567049:ios:2b8c2496aa96fddddca558',
    messagingSenderId: '924490567049',
    projectId: 'x-me-297fb',
    storageBucket: 'x-me-297fb.firebasestorage.app',
    iosBundleId: 'com.example.me',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnnmYOADL2XoSSVyP9wxPo5ZmiuNiWz5Y',
    appId: '1:924490567049:web:8a7e3da9bc5a9257dca558',
    messagingSenderId: '924490567049',
    projectId: 'x-me-297fb',
    authDomain: 'x-me-297fb.firebaseapp.com',
    storageBucket: 'x-me-297fb.firebasestorage.app',
    measurementId: 'G-TYXNLTG0FG',
  );
}
